### PR TITLE
plugin: stop overriding user preferences

### PR DESCRIPTION
**Pull request by dcousens**
Fixes https://github.com/toddbluhm/cordova-plugin-launchscreen-storyboard/issues/3

### CODE REVIEW

**Comment by dcousens** [comment]
@toddbluhm if you plan to,  please post here if you publish so I can avoid using my fork :+1:

**Comment by toddbluhm** [comment]
@dcousens Yeah I plan to publish tonight. I am going to update the README and remove the deprecation warning and suggest using it with `CDVLaunchScreen`. Also I plan to update the default to use `CDVLaunchScreen` instead of the current default. It will be a major version bump as its a breaking change.

**Comment by toddbluhm** [comment]
@dcousens `2.0.0` should be live now. It includes this PR and the change to use `CDVLaunchScreen ` as the default. I also added your name to the README and package.json as a contributor if thats okay with you? Let me know if you run into any issues. I also wanted to apologize for the late merge of this. I got busy over the holidays and did not spend much time working OSS projects.

**Comment by dcousens** [comment]
thanks @toddbluhm!  Hardly late,  t'is the holiday season :)

**Pull request merged**
